config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks do
    member do
      patch :complete
      patch :reorder
      patch :pending
    end

    collection do
      get :completed
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tasks#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "dashboard_charts", type: "module" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", media: "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container">
        <%= link_to "TodoApp", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to "Görevler", tasks_path, class: "nav-link #{'active' if current_page?(tasks_path)}" %>
            </li>
            <li class="nav-item">
            <li class="nav-item">
              <%= link_to "Tamamlananlar", completed_tasks_path, class: "nav-link #{'active' if current_page?(completed_tasks_path)}" %>
            </li>
            <li class="nav-item">
              <%= link_to "Kategoriler", categories_path, class: "nav-link #{'active' if current_page?(categories_path)}" %>
            </li>
          </ul>
          <div class="d-flex">
            <%= link_to "Yeni Görev", new_task_path, class: "btn btn-success me-2" %>
            <%= link_to "Yeni Kategori", new_category_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>